import "dotenv/config";
import express from "express";
import http from "http";
import startServer from "./app.js";
import erroHandler from "../src/middleweare/errorHandller.js";
const app = express();
app.use(express.json());
const server = http.createServer(app);
app.use(erroHandler);
const PORT = process.env.PORT;
startServer(server);